### PR TITLE
BLD: move package to noarch

### PR DESCRIPTION
**Pull request by klauer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Supersedes #16 

Changes based on Nikea Slack discussion:

* Switched to noarch
* Python 3.8+ is OK per @tacaswell and @mrakitin: this means that `typing-extensions` is no longer required (NEP 29 https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table)
    * Pinned Python as a build and run dependency to `>=3.8`
* Windows builds will fail due to bluesky-kafka not being available (letting it fail is OK per @mrakitin )
   * Queue server does not run on Windows anyway according to @dmgav

cc @tangkong

### CODE REVIEW

**Comment by tacaswell** [comment]
@conda-forge-admin please rerender

**Comment by klauer** [comment]
I did a re-render locally with the latest conda-smithy (a no-op because it was up-to-date from the previous PR), but it can't hurt to re-run it

**Comment by tacaswell** [comment]
If it is no-arch it should not be running this many CI jobs (I think?) I was hoping the re-render would cut most of those out...

**Comment by klauer** [comment]
Good call - and odd that it said it was up-to-date already. Ah, conda-build was behind:
```
INFO:conda_smithy.configure_feedstock:Re-rendered with conda-build 3.21.9, conda-smithy 3.22.1, and conda-forge-pinning 2023.01.27.16.18.18
INFO:conda_smithy.configure_feedstock:No changes made. This feedstock is up-to-date.
```
A good reminder to myself to always rely on the bot and not bother with local fix-ups

**Review by tacaswell — APPROVED** [review]

**Review by dmgav — APPROVED** [review]

**Review by mrakitin — APPROVED** [review]

**Pull request merged**
